version: '3.1'

services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
